<?php
/**
 * 
 * Author: Roberto Lombi
 * Date: 22/08/14
 * Time: 21:36
 *
 * Email: signoramiailmio@robertodormepoco.org
 * Website: http://www.robertodormepoco.org
 */

namespace Issuu\Exceptions;


use Exception;

class NotUniqueDocumentException extends \RuntimeException {
    public function __construct($message = "", $code = 0, Exception $previous = null)
    {
        parent::__construct($message, $code, $previous); // TODO: Change the autogenerated stub
    }


} 